### PR TITLE
resolving git remote issues

### PR DESCRIPTION
**Pull request by nicolasmarino99**
I did a remote fetch instead of a clone, therefore the master branch and develop branch didn´t share the same history, thus i couldn´t make a pull request. I clone this repo, deleted the develop branch and created another one to have a pull request, that´s why i only have one commit

### CODE REVIEW

**Comment by Oghenebrume50** [comment]
Hi Nicholas,  great start to this project, currently the page doesn't display properly the last image among the four images displayed before the footer overlaps to the bottom please fix this. Then follow these guidelines to  fix other issues

## Main content links
 - [x] There should be three links
 - [x] Each link is an <a> HTML tag, with a <div> tag inside it.
  - [x] The <div> tag  inside the <a> tag should use an image as background, The text on the original page is actually an image

currently, you are passing the images as a child to the div element please fix this with the above steps.

## footer
- [x] It should be wrapped by `<footer>` tags
- [ ] The top part is made of four `<a>` tags with `<div>` tags inside it
- [ ] The `<div>`s inside the `<a>` tags should use an image as a background
- [x] The bottom part should include links like copyright, terms of use, and privacy policy

Following the steps above every thing in the div with id as  `img-products`  should go in the footer then pass the images as background images instead.

## Background
- [ ] The main content should be wrapped around `<main>` tags and have an image set as background

## Navbar
- [x] It should be within the `<main>` tag

Fix the above and submit for re-review, Kudos for a good start

**Comment by Torres-ssf** [comment]
Pull Request Under Review By Sérgio (TSE)

**Comment by Torres-ssf** [comment]
Hi there @nicolasmarino99 
You are almost done with this project. We only need to make some changes to be in line with Microverse guidelines. 

- [x] Microverse guidelines require a different approach from the original page for loading image. You must load all images in a div tag, using the background. This applies to the 3 main sentences and all 4 promo images. 

- [x] Use div tag instead img tag to load the image for the 3 main sentences.

- [x] Microverse guidelines require the 4 promo images inside the footer. The footer should be divided in two parts, top, and bottom. The 4 promo images should be inside the top part of the footer.

- [x] Use div tag instead img tag to load the images for the 4 promo images.

Please kindly make these changes and submit for code review again.

**Comment by Torres-ssf** [comment]
### Pull Request Under Review By Sérgio (TSE)

**Comment by Torres-ssf** [comment]
### Nicely done @nicolasmarino99 
You worked alot on this project and should be proud of it. I'm giving this project a 👍. Go ahead and merge to master. Good luck with the next one.

**Pull request merged**
